### ISSUE TITLE
Data Artefact Schema

### ISSUE THREAD

**Issue by sjperkins** [ratt-ru/packratt#1]
packratt is both an application and python package for downloading and caching radio astronomy data artefacts, primarily to facilitate testing radio astronomy software.

I propose using the following schemas to uniquely identify data artefacts for download

```bash
packratt get /ms/<telescope>/<observation_date>/<filename> <target_dir>
packratt get /uvfits/<telescope>/<observation_date>/<filename> <target_dir>
packratt get /beams/<telescope>/<filename> <target_dir>
packratt get /gains/<telescope>/<observation_date>/<filename> <target_dir>
```

```python
import packratt
packratt.get("/ms/<telescope>/<observation_date>/<filename>", target_dir)
packratt.get("/uvfits/<telescope>/<observation_date>/<filename>", target_dir)
packratt.get("/beams/<telescope>/<filename", target_dir)
packratt.get("/gains/<telescope>/<observation_date>/<filename>", target_dir)
```

The above schemas create keys which uniquely identify an artefact to download and cache, defined in a yaml registry:

```yaml
"/ms/<telescope>/<observation_date>/<filename>":
    "type": "url"
    "url": ftp://elwood.ru.ac.za/pub/astronomer/observation.tar.gz
    "hash": "1234567890abcdef"

"/ms/<telescope>/<observation_date>/<filename>":
    "type": "google"
    "file_id": "1234567890"
    "hash": "1234567890abcdef"
```

/cc @o-smirnov @smasoka @SpheMakh @svw26 @bennahugo @jskenyon @Athanaseus @landmanbester @gigjozsa @IanHeywood @mulan-94
